### ISSUE TITLE
about the code GBNet

### ISSUE THREAD

**Issue by amiltonwong** [ShiQiu0419/GFNet#1]
Hi, @ShiQiu0419 ,

When will you release the code?

THX!

**Comment by ShiQiu0419** [comment]
> Hi, @ShiQiu0419 ,
> 
> When will you release the code?
> 
> THX!

Hi,

We will release the codes once the paper gets officially published (recently we updated on arXiv for v3). Please stay tuned.

If you have any question about the paper contents, please feel free to propose another issue for discussion.
 
Thanks for you interest.

**Comment by amiltonwong** [comment]
Have good result :)
