### ISSUE TITLE
Hi! When will you release the code?

### ISSUE THREAD

**Issue by DLwbm123** [ShiQiu0419/GFNet#2]

**Comment by ShiQiu0419** [comment]
Hi, thanks for your interests. According to the policy of our institution, the codes can be released after the work is officially published. Unfortunately, the paper is still under review of a journal, we hope it can be finalized soon.&nbsp;


------------------ Original ------------------

**Comment by ShiQiu0419** [comment]
Hi @DLwbm123 ,

Both the codes and pre-trained models for point cloud classification including ModelNet40 and ScanObjectNN datasets are fully avaible now. Thanks for your attention!
